edowardo/swapsies

config/routes.rb
=> added routes to project

app/models/game.rb, db/migrate/20191111074630_create_games.rb, test/models/game_test.rb
I added the game model and migration, plus added some validations and associations
=> Add game model

app/models/listing.rb, db/migrate/20191111083450_create_listings.rb, db/schema.rb, test/models/listing_test.rb
Added the listing model... pls check syntax for default status
=> added Listing model

app/models/swap.rb, db/migrate/20191111090535_create_swaps.rb, db/schema.rb, test/models/swap_test.rb
It probably doesn't work, but do it anyway
=> validations and associations incomplete

.gitignore, Gemfile, Gemfile.lock, app/controllers/games_controller.rb, app/controllers/pages_controller.rb, config/routes.rb, db/seeds.rb, test/controllers/games_controller_test.rb
I seeded the database and updated the games controller
=> Creating games controller

app/views/games/index.html.erb
I added a view page for games#index
=> added show page for home

app/views/games/index.html.erb
Just limited the number of games to be show to 100
=> limited games on the index page to 100

app/views/games/show.html.erb
=> created games show page

app/controllers/games_controller.rb, config/routes.rb
=> added show controller action and route for game

config/routes.rb, db/schema.rb
fixed typo and added index route to games
=> Create game show page

app/controllers/games_controller.rb, app/views/games/index.html.erb, app/views/games/show.html.erb
Added links to index taht leads to show page 
added links to show age that leads to index
limited loading of database to 20 so it won't crash
=> Added links

app/controllers/swaps_controller.rb, config/routes.rb, test/controllers/swaps_controller_test.rb
Probably working in part, but at least some of it will be broken
=> Add swaps controller

app/views/games/index.html.erb
=> Added card

app/views/games/show.html.erb
added listings to game show page
=> listing code added in game show page

app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/config/_fonts.scss, app/assets/stylesheets/pages/_index.scss, app/controllers/games_controller.rb, app/views/games/index.html.erb
changed fonts, added search bar and chnaged background color
=> changed fonts, added search bar and chnaged background color

app/controllers/listings_controller.rb, app/views/listings/new.html.erb
Should all be working. Navigation options minimal
=> Add new listing view

app/views/shared/_navbar.html.erb
=> added logout button to navbar

app/assets/stylesheets/components/_card.scss, app/controllers/users_controller.rb, app/views/games/index.html.erb
I made beautiful cards on the index page
=> I made beautiful cards on the index page

app/controllers/swaps_controller.rb
Should redirect to user once create swap action is complete
=> should work now

app/assets/javascripts/application.js, app/assets/stylesheets/components/_navbar.scss, app/javascript/components/navbar.js, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
=> fixed navbar scrolling issue

app/controllers/listings_controller.rb
=> fixed route after creating listing

app/assets/stylesheets/components/_card.scss, app/controllers/application_controller.rb, app/uploaders/photo_uploader.rb, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb
User image upload should now work. I added some styling for the navbar avatar and user show image. 
REFER TO SLACK  to get the key for Noah's Cloudinary, and add it to your env file. Otherwise, no es work.
=> User image upload

app/assets/stylesheets/components/_avatar.scss, app/views/shared/_navbar.html.erb, app/views/users/show.html.erb, db/schema.rb
=> now works with default user image when user does not upload

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_general.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_fonts.scss, app/views/games/show.html.erb, app/views/listings/new.html.erb, app/views/swaps/new.html.erb
you can now put things in a plain field to make them stand out from the background. This should especially be used for 'static' data, that the user is not expecting to interact with.
=> added plain-field and altered fonts
